### ISSUE TITLE
[ENG-2816] [FEATURE REQUEST] Automatically create directory when creating S3 Integration

### ISSUE THREAD

**Issue by CesarDNDN** [aqueducthq/aqueduct#1211]
**Problem**
I'm attempting to create a new AWS S3 configuration that will store the aqueduct metadata. I'd like to use a subdirectory for the storage, but I get the following error when connecting the integration:
`Exception: Supplied root directory aqueduct/ does not exist in bucket <bucket name>.`

**Solution**
It'd be beneficial to have the subdirectory automatically created if it does not exist.

**Alternatives**
If having the subdirectory automatically created is not desirable, having it as a optional checkbox underneath directory would also be a possible solution.

<sub>[ENG-2816](https://linear.app/aqueducthq/issue/ENG-2816/[feature-request]-automatically-create-directory-when-creating-s3)</sub>

**Comment by kenxu95** [comment]
Giving this to Jerome to get him exposure to the python executor operators.

**Comment by kenxu95** [comment]
@jerome take a look around line 42 of `aqueduct_executor/operators/connectors/data/s3.py`

**Comment by sravoor** [comment]
Ignore: test comment to verify Linear & github syncing

**Comment by sravoor** [comment]
@jpurusho65 seeking confirmation that this PR Is still open and did not make the Mon 11PM cut-off.

Kindly update stale due date and release label accordingly.

Please also share what kind of complexity is holding up this PR - out for review from 8 days ago.

**Comment by jpurusho65** [comment]
I have moved the due data to tomorrow. We had some back & forth on test integration for this, and found it was not straightforward to add that. Decided to move that change to a separate issue.

**Comment by jpurusho65** [comment]
The primary change itself is good and was verified with our UI early on, and confident to push yesterday, but got held up because of adding s3 integration test.

**Comment by jpurusho65** [comment]
Created new issue  [ENG-2946](https://linear.app/aqueducthq/issue/ENG-2946/add-s3-data-integration-test-for-root-folder-creation) to track test changes
