### ISSUE TITLE
[ENG-2760] Merge id and name arguments into one for `client.flow()`

### ISSUE THREAD

**Issue by kenxu95** [aqueducthq/aqueduct#1239]
To fetch by name, I have to use `client.flow(flow_name="…")`, which is quite redundant. Let's just use the signature `def flow(self, flow_identifier)`

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-2760](https://linear.app/aqueducthq/issue/ENG-2760/merge-id-and-name-arguments-into-one-for-clientflow)</sub>

**Comment by sravoor** [comment]
@jpurusho65 focus on the GKE project first and then come back to these tasks

**Comment by vsreekanti** [comment]
@jpurusho65 @sravoor, this should be super quick, so let's tackle it in next week's on call work.

**Comment by jpurusho65** [comment]
Sure will take care of this

**Comment by sravoor** [comment]
from @saurav-c on slack:

won’t this break existing notebooks that are using named arguments for `flow_id` or `flow_name`, since they’re being replaced by `flow_identifier`? Should we roll out this API change more gradually and give a deprecation warning?

@vsreekanti @kenxu95 @jpurusho65  ^^^^

**Comment by vsreekanti** [comment]
Yes, 100% agree with Saurav.

**Comment by kenxu95** [comment]
Should we reopen this task then? @sravoor

**Comment by kenxu95** [comment]
Created the new task ENG-3007

**Comment by jpurusho65** [comment]
I changed the API's to be backward compatible, and created another task [ENG-3013](https://linear.app/aqueducthq/issue/ENG-3013/deprecate-flow-id-and-flow-name-completely) to track complete removal of the deprecated parameters in a future release. The API now throws a deprecated warning to end user. PR is out for review, will be checked in shortly.
