### ISSUE TITLE
[BUG] Mongo data couldn't be previewed

### ISSUE THREAD

**Issue by likawind** [aqueducthq/aqueduct#809]
**Description**
Mongo collections couldn't be previewed:

<img width="1100" alt="Screen Shot 2022-12-14 at 11 08 41 AM" src="https://user-images.githubusercontent.com/10411887/207701323-547cf653-8d1f-4417-8bec-81602571d802.png">

**Steps to reproduce the behavior**
1. Connect to a mongo database with existing collections
2. Expand any collection in 'Data' section
3. The preview of that collection would fail

**Comment by vsreekanti** [comment]
Resolved as of v0.1.7.
